# Generated by Django 4.0.1 on 2022-02-02 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('title_tag', models.CharField(blank='True', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('post_description', models.CharField(default='Description', max_length=500)),
                ('text_post', models.TextField(blank=True, verbose_name='Contenu')),
                ('created_date_post', models.DateField(blank=True, null=True)),
                ('category', models.CharField(default='devlog', max_length=100)),
                ('pusblished', models.BooleanField(default=False, verbose_name='Publié')),
                ('picture', models.ImageField(default='None', upload_to='post_img')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, default=[0], related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-created_date_post'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=1000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('downvote', models.ManyToManyField(blank=True, default=[0], related_name='downvote', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.postblog')),
                ('upvote', models.ManyToManyField(blank=True, default=[0], related_name='upvote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
